server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/iot_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health
    endpoint:
      health:
        show-details: always